name: tobias_package_env

channels:
  - bioconda
  - conda-forge

dependencies:
  - python > 3
  - pysam
  - pybigwig
  - moods
  - pybedtools
  - cython
  - matplotlib
  - numpy
  - scipy
  - pypdf2
  - scikit-learn
  - gimmemotifs
  - pyyaml
  - boto3
  - pip
  - pip: 
    - adjustText
